unit pokemon;

interface

uses crt;
procedure affiche_pokemon(pokemon:string);

var px, py : integer;

implementation

procedure affiche_pokemon(pokemon:string);

BEGIN
	px := 50;
	py := 5;

		case (pokemon) of

			'Salameche' :
							begin
								delay(10);
								writeln('                     _.--""`-.                                                 ');
								delay(10);
								writeln('                   ,           `.                                              ');
								delay(10);
								writeln('                 ,           __   .                                            ');
								delay(10);
								writeln('                /|          " __   \                                           ');
								delay(10);
								writeln('               , |           / |.   .                                          ');
								delay(10);
								writeln('               |,           !_. |   |                                          ');
								delay(10);
								writeln('             ,                  |   |                                          ');
								delay(10);
								writeln('            /              |`-- |   |                                          ');
								delay(10);
								writeln('           |                `---    |                                          ');
								delay(10);
								writeln('            .   ,                   |                       ,".                ');
								delay(10);
								writeln('             ._                 _   |                    ,   \ `               ');
								delay(10);
								writeln('         `.. `.`-...___,...---""    |       __,.        ,`"   L,|              ');
								delay(10);
								writeln('         |, `- .`._        _,-,.    .  __.- -. /        .   ,    \             ');
								delay(10);
								writeln('       -:..     `. `-..--_.,.<       `"      / `.        `-/ |   .             ');
								delay(10);
								writeln('         `,         """"      `.              ,          |   |   ,,            ');
								delay(10);
								writeln('           `.                                /               | . |/            ');
								delay(10);
								writeln('             `.   |              \       _,-            |                      ');
								delay(10);
								writeln('               `._                \    "\                .      |              ');
								delay(10);
								writeln('                  |                      \                `._  ,               ');
								delay(10);
								writeln('                  |                       \                 . |                ');
								delay(10);
								writeln('                  |                 .      \                | |                ');
								delay(10);
								writeln('                  |                 |       L              ,  |                ');
								delay(10);
								writeln('                  `                 |       |             /                    ');
								delay(10);
								writeln('                   \                |       |           ,    /                 ');
								delay(10);
								writeln('                 ,  \               |  _.._ ,-..___,..-     ,                  ');
								delay(10);
								writeln('                /     .             .      `!             ,j                   ');
								delay(10);
								writeln('               /       `.          /        .           . /                    ');
								delay(10);
								writeln('              .          `.       /         |        _. .                      ');
								delay(10);
								writeln('               `.          7` ---           |------" _.                        ');
								delay(10);
								writeln('              _,.`,_     _                 ,  -----"                           ');
								delay(10);
								writeln('          _,-_            `.     .       ,\                                    ');
								delay(10);
								writeln('          -" /`.         _,      | _  _  _.|                                   ');
								delay(10);
								writeln('           ""-- ---"""""         `   ! |! /                                    ');
								delay(10);
								writeln('                                   `" "                                        ');
							end;


			'Carapuce'	:
							begin
								writeln('                 _,........__                                                  ');
								delay(10);
								writeln('              ,-             "`-.                                              ');
								delay(10);
								writeln('            ,                    `-.                                           ');
								delay(10);
								writeln('          ,                         \                                          ');
								delay(10);
								writeln('        ,                            .                                         ');
								delay(10);
								writeln('        . \               ,"".       `                                         ');
								delay(10);
								writeln('       ._. |             / |  `       \                                        ');
								delay(10);
								writeln('       |   |            `-.   ||       `.                                      ');
								delay(10);
								writeln('       |   |             -._, ||       | \                                     ');
								delay(10);
								writeln('       .`.,              `.., .        , |`-.                                  ');
								delay(10);
								writeln('       l                       . `.  _/  |   `.                                ');
								delay(10);
								writeln('       `-.._ -   ,          _ _    -" \  .     `                               ');
								delay(10);
								writeln('  `.""""" -.`-...,--------- ,          `. `....__.                             ');
								delay(10);
								writeln('  .         `"-..___      __, \          \  \     \                            ');
								delay(10);
								writeln('  \_ .          |   `""""     `.           . \     \                           ');
								delay(10);
								writeln('    `.          |              `.          |  .     L                          ');
								delay(10);
								writeln('      `.        |`--...________. .        j   |     |                          ');
								delay(10);
								writeln('        `._    .       |          `.     .|   ,     |                          ');
								delay(10);
								writeln('           `--,\       .            `7""  |  ,      |                          ');
								delay(10);
								writeln('              ` `      `            /     |  |      |    _,- """`-.            ');
								delay(10);
								writeln('               \ `.     .          /      |         |  ,           `.          ');
								delay(10);
								writeln('                \  v.__  .                .   \    /| /              \         ');
								delay(10);
								writeln('                 \/    `""\"""""""`.       \   \  /.                  |        ');
								delay(10);
								writeln('                  `        .        `._ ___,j.  `/ .-       ,---.     |        ');
								delay(10);
								writeln('                  ,`-.      \         ."     `.  |/        j     `    |        ');
								delay(10);
								writeln('                 /    `.     \       /         \ /         |     /    j        ');
								delay(10);
								writeln('                |       `-.   7-.._ .          |"                    /         ');
								delay(10);
								writeln('                |          `./_    `|          |            .     _,           ');
								delay(10);
								writeln('                `.           / `----|          |-............`---              ');
								delay(10);
								writeln('                  \          \      |          |                               ');
								delay(10);
								writeln('                 ,            )     `.         |                               ');
								delay(10);
								writeln('                  7____,,..--       /          |                               ');
								delay(10);
								writeln('                                    `---.__,--.                                ');
							end;

			'Bulbizarre':
							begin
								delay(10);
								writeln('                                               /                               ');
								delay(10);
								writeln('                            _,.------....___,.   ,.-.                          ');
								delay(10);
								writeln('                         ,-           _,.--"        |                          ');
								delay(10);
								writeln('                       ,          _.-               .                          ');
								delay(10);
								writeln('                      /   ,     ,                    `                         ');
								delay(10);
								writeln('                     .   /     /                     ``.                       ');
								delay(10);
								writeln('                     |  |     .                       \.\                      ');
								delay(10);
								writeln('           ____      |___._.  |       __               \ `.                    ');
								delay(10);
								writeln('         .     `---""       ``"-.--" `  \               .  \                   ');
								delay(10);
								writeln('        .  ,            __               `              |   .                  ');
								delay(10);
								writeln('        `,          ,-"   .               \             |    L                 ');
								delay(10);
								writeln('       ,                _.                 -._          /    |                 ');
								delay(10);
								writeln('      ,`-.    ,".   `--                       >.      ,      |                 ');
								delay(10);
								writeln('     . . \    `-        __    ,  ,-.         /  `.__.-      ,                  ');
								delay(10);
								writeln('     ||:, .           ,      /  / \ `        `.    .      . /                  ');
								delay(10);
								writeln('     j|:D  \          `--     , _  . .         `.__, \   , /                   ');
								delay(10);
								writeln('    / L:_  |                 .  "  :_                 `. .                     ');
								delay(10);
								writeln('    .    ""                   """""                     V                      ');
								delay(10);
								writeln('     `.                                 .    `.   _,..  `                      ');
								delay(10);
								writeln('       `,_   .    .                _,- /    .. `,    __  `                     ');
								delay(10);
								writeln('        ) \`._        ___....----"   ,    .   \ |      \  .                    ');
								delay(10);
								writeln('       /   `. "`-.--"          _,  ,      `---  |    `./  |                    ');
								delay(10);
								writeln('      .   _  `"" --.._____..--"   ,                       |                    ');
								delay(10);
								writeln('      | ." `. `-.                /-.           /          ,                    ');
								delay(10);
								writeln('      | `._.     `,_               /         ,           .                     ');
								delay(10);
								writeln('     .           /| `-.        . ,          ,           ,                      ');
								delay(10);
								writeln('      -.__ __ _, ,      `-..___ -...__   ,. \ ____.___.                        ');
								delay(10);
								writeln('     `"^-- ..     -`-^- "--    `-^- `.  """""`.,^.`.--                         ');
							end;

			'Roucool'	:
							begin
								delay(10);
								writeln('                      .,                                                       ');
								delay(10);
								writeln('               , _.- ,                                                         ');
								delay(10);
								writeln('             ""|"    `"""".,                                                   ');
								delay(10);
								writeln('            / /       __.- -"/                                                 ');
								delay(10);
								writeln('            ,   _,--""       -._                                               ');
								delay(10);
								writeln('       _...`... ."""""".\""-----                                               ');
								delay(10);
								writeln('    ,-           `-.) /  `.  \                                                 ');
								delay(10);
								writeln('   +---."-.    |     `.    .  \                                                ');
								delay(10);
								writeln('        \  `.  |       \   |   L                                               ');
								delay(10);
								writeln('         `v  ,-j        , .    |                                               ');
								delay(10);
								writeln('        . \,  /        /,       -._                                            ');
								delay(10);
								writeln('       ,____.         .            `-.                                         ');
								delay(10);
								writeln('           |         /                `-.                                      ');
								delay(10);
								writeln('          /          `.                  `-.                                   ');
								delay(10);
								writeln('         /             `. |                 `.                  _.             ');
								delay(10);
								writeln('        .                `|                 ,-.             _.-" .             ');
								delay(10);
								writeln('       j                  |                 |  \         _.     /              ');
								delay(10);
								writeln('       .                  |               .     \     ,-       /               ');
								delay(10);
								writeln('       |                  |            ,-.\      \  ,       _.-                ');
								delay(10);
								writeln('       |                .    `.       |   `      `v   _,.-"/                   ');
								delay(10);
								writeln('       ||    \          |  ` |(` -`.,.j         \ `.- ----+---.                ');
								delay(10);
								writeln('       | |   |L    \  | |   `|   \               L \___      /                 ');
								delay(10);
								writeln('         L   |`     L | |     `.                 | j   `"""-                   ');
								delay(10);
								writeln('          `- ||\    | ||j       `.       ._    `  .                            ');
								delay(10);
								writeln('             `\  "`^"-            `.       \    |/|                            ');
								delay(10);
								writeln('               `._                  `-.     \   Y |                            ');
								delay(10);
								writeln('       __,..-""`..`._                  `-._  `\ `.|                            ');
								delay(10);
								writeln('      +.....>+----.  ""----.........,--""" `--. .                              ');
								delay(10);
								writeln('          ,  _\  ,..--.-"  __>---   |                                          ');
								delay(10);
								writeln('         --""  "   _." }<""          `---""`._                                 ');
								delay(10);
								writeln('                  /..."  L__.+--   _,...... ..                                 ');
								delay(10);
								writeln('                    /.-"" /   \ ,-                                             ');
								delay(10);
								writeln('                        .  ,-""                                                ');
								delay(10);
								writeln('                       /.-                                                     ');
							end;

			'Ratata'	:
							begin
								delay(10);
								writeln('                                       , ""`--.                                ');
								delay(10);
								writeln('                                      |     __ `-.                             ');
								delay(10);
								writeln('                                      |    /  `.  `.                           ');
								delay(10);
								writeln('                                       \        ,   `.                         ');
								delay(10);
								writeln('                                        `.      \_    `.                       ');
								delay(10);
								writeln('                                          `.    | `.    \                      ');
								delay(10);
								writeln('                                            `--"    `.   `                     ');
								delay(10);
								writeln('                                                      `.  `                    ');
								delay(10);
								writeln('                  ,.._                                  \  `                   ');
								delay(10);
								writeln('                /_,.  `.                                 \  `                  ');
								delay(10);
								writeln('               j/   .   \                  ___            \  \                 ');
								delay(10);
								writeln('               |    |   `____         _,--    `.           .  L                ');
								delay(10);
								writeln('                L  /`--"     ` --._ ,    ,-` \ |            . |                ');
								delay(10);
								writeln('                 |-                 /  ,      ||            | |                ');
								delay(10);
								writeln('      -v._      /                   ,         ||            | |                ');
								delay(10);
								writeln('        `.`-._,                _     \        |j    _,...   | |                ');
								delay(10);
								writeln('          `,.              _,-. \     |      /,---""     `- | |                ');
								delay(10);
								writeln('         .               ,".   ||     `..___/,             `  |                ');
								delay(10);
								writeln('         |   ,         _/`-   /,                             `|                ');
								delay(10);
								writeln('         |-.__.- "  ""  """"""""--`_,...-----    --...--      `.               ');
								delay(10);
								writeln('          `.____,..              ""   __,..---"""              |               ');
								delay(10);
								writeln('           |       `              --" .                        `               ');
								delay(10);
								writeln('           |     ,  `._                \                        `              ');
								delay(10);
								writeln('           | |  .^.    `.             /                          `.            ');
								delay(10);
								writeln('          , _]__|  \   / `.          /          /____._            `._         ');
								delay(10);
								writeln('        ,           \ j             /          /       `.             `.       ');
								delay(10);
								writeln('  ___,.  `._       __L/    |     __           /     _, / \             |       ');
								delay(10);
								writeln('  -._       L,.-"""  .    ,  _.- ,           /----- -./   `--.         |       ');
								delay(10);
								writeln('        / ,           .. "_,     /         F /  ." _,         |.__     |       ');
								delay(10);
								writeln('   / ,.\,               ""      /         / (, \ .         ,.-"   `.  j        ');
								delay(10);
								writeln('   -                           /        ,      `"         / __/  .- ,          ');
								delay(10);
								writeln('                            __. "`.    /                 `-  | _,L,            ');
								delay(10);
								writeln('                          . ,      `""                        /,--             ');
								delay(10);
								writeln('                           / _..  _,,                                          ');
								delay(10);
								writeln('                           ,  `-"                                              ');
							end;

			'Pikachu'	:
							begin
								delay(10);
								writeln('                                               ,-.                             ');
								delay(10);
								writeln('                                            _.|  /                             ');
								delay(10);
								writeln('                                          .   | /                              ');
								delay(10);
								writeln('                                        ,     |/                               ');
								delay(10);
								writeln('                                       /      /                                ');
								delay(10);
								writeln('                         _..----""---.       /                                 ');
								delay(10);
								writeln('   _.....---------...,-""                  ,                                   ');
								delay(10);
								writeln('   `-._  \                                /                                    ');
								delay(10);
								writeln('       `-.+_            __           ,--. .                                    ');
								delay(10);
								writeln('            `-.._     .:  ).        (`--"| \                                   ');
								delay(10);
								writeln('                 7    | `" |         `...   \                                  ');
								delay(10);
								writeln('                 |     `--       +"        ,". ,""-                            ');
								delay(10);
								writeln('                 |   _...        .____     | |/    \                           ');
								delay(10);
								writeln('            _.   |  .    `.   --"   /      `./     j                           ');
								delay(10);
								writeln('           \  `-.|        |   `.   /        /     /                            ');
								delay(10);
								writeln('                 `-. `---"      `-"        /     /                             ');
								delay(10);
								writeln('            \       `.                  _,      /                              ');
								delay(10);
								writeln('             \        `                        .                               ');
								delay(10);
								writeln('              \                                j                               ');
								delay(10);
								writeln('               \                              /                                ');
								delay(10);
								writeln('                `.                           .                                 ');
								delay(10);
								writeln('                  +                          \                                 ');
								delay(10);
								writeln('                  |                           L                                ');
								delay(10);
								writeln('                  |                           |                                ');
								delay(10);
								writeln('                  |  _ /,                     |                                ');
								delay(10);
								writeln('                  | | L) ..                   |                                ');
								delay(10);
								writeln('                  | .    | `                  |                                ');
								delay(10);
								writeln('                     \    L                                                    ');
								delay(10);
								writeln('                   \  \   |                  j                                 ');
								delay(10);
								writeln('                    `. `__                  /                                  ');
								delay(10);
								writeln('                  _,.--.---........__      /                                   ');
								delay(10);
								writeln('                 ---., ---`         |   -j"                                    ');
								delay(10);
								writeln('                  .-    ....__      L    |                                     ');
								delay(10);
								writeln('                ""--..    _,-        \ l||                                     ');
								delay(10);
								writeln('                    ,-   .....------. `||                                      ');
								delay(10);
								writeln('                 _,                 /                                          ');
								delay(10);
								writeln('               ,                   /                                           ');
								delay(10);
								writeln('               ---------+-        /                                            ');
								delay(10);
								writeln('                       /         /                                             ');
								delay(10);
								writeln('                     .          /                                              ');
								delay(10);
								writeln('                   .           /                                               ');
								delay(10);
								writeln('                 ,            /                                                ');
								delay(10);
								writeln('               _/....----"""""                                                 ');
							end;

			'Machoc'	:
							begin
								delay(10);
								writeln('                             ,."--.                                             ');
								delay(10);
								writeln('                        _.../     _\""-.                                        ');
								delay(10);
								writeln('                      //  ,     ,"      :                                       ');
								delay(10);
								writeln('                     .   /   .:       __|                                       ');
								delay(10);
								writeln('                     || ||  /,    _."    .                                      ');
								delay(10);
								writeln('                     || ||  ||  ,         `.                                    ');
								delay(10);
								writeln('                    /|| ||  ||,             .                                   ');
								delay(10);
								writeln('                   /.`| /` /`,   __                                             ');
								delay(10);
								writeln('                  j /. " `"    ,  /`.        |                                  ');
								delay(10);
								writeln('                  ||.|        .  | . .      _|,--._                             ');
								delay(10);
								writeln('                  ||#|        |  | # |   ,-"       `-.                          ');
								delay(10);
								writeln('                 / .||        |  \." |  /             `                         ');
								delay(10);
								writeln('                /             `.----"   |`.|           |                        ');
								delay(10);
								writeln('                \  `.    ,              `  \           |                        ');
								delay(10);
								writeln('                 `._____           _,-   `._,..        |                        ');
								delay(10);
								writeln('                   `".  ` -..__..-    _,.-- .  .       |                        ');
								delay(10);
								writeln('                    ,-^-._      _,..-        `.|       |                        ');
								delay(10);
								writeln('                _,-      | "" ""              `|  `\    \                       ');
								delay(10);
								writeln('            _.-          |            `.,--    |    \    \                      ');
								delay(10);
								writeln('       _,."" "" -._             `.     .      j           \                     ');
								delay(10);
								writeln('      /            `.___/.-"    ._`-._  \.    |      |     L                    ');
								delay(10);
								writeln('     /  ____           /,.-     . `._  ""|`.  `      |     |                    ');
								delay(10);
								writeln('      `.    `"-.      / _,-"     `._ `" ".  `. \                                ');
								delay(10);
								writeln('        \       `-   ."             "`--- \   ` `-._/     /                     ');
								delay(10);
								writeln('         `-------.   |                     \   `-._      /                      ');
								delay(10);
								writeln('                  \ j                      .       `...,                        ');
								delay(10);
								writeln('                   `|                       \                                   ');
								delay(10);
								writeln('                                             \                                  ');
								delay(10);
								writeln('                     .                      / \                                 ');
								delay(10);
								writeln('                     |`.                   /   `._                              ');
								delay(10);
								writeln('                     |    `.._____        /|      `-._                          ');
								delay(10);
								writeln('                     |        |   Y.       |.         `.                        ');
								delay(10);
								writeln('                     |       j     \        .`"--....-                          ');
								delay(10);
								writeln('                  _,-        |      |        \                                  ');
								delay(10);
								writeln('               .-            |     ,          `.                                ');
								delay(10);
								writeln('                             |     |            `.                              ');
								delay(10);
								writeln('              `.        __,..       .             \                             ');
								delay(10);
								writeln('                `-.---"              `-..__      _/                             ');
								delay(10);
								writeln('                                           ` """                                ');
							end;

			'Racaillou':
							begin
								delay(10);
								writeln('                                               _,.---.                          ');
								delay(10);
								writeln('                                           _,-        `.                        ');
								delay(10);
								writeln('                                        _,   ,          \                       ');
								delay(10);
								writeln('                                      ,   _,    .        `.                     ');
								delay(10);
								writeln('                                     /  ,      ,           `.                   ');
								delay(10);
								writeln('            __                       .,     _,               `.                 ');
								delay(10);
								writeln('       _,..   `-....___              :    ,                    \                ');
								delay(10);
								writeln('     ,    /            :             /`.,       /               `               ');
								delay(10);
								writeln('    /    /  ._         |         __..|  `.    .        ,         `.             ');
								delay(10);
								writeln('    |   |   , "--._    |      ,-     `-._`.,-        ,:            .            ');
								delay(10);
								writeln('   . \   \     _, .    ` ___.            `"`.     _,  /            |            ');
								delay(10);
								writeln('   |  \   \---        ,"   .-"" "----.       `.     ,              |            ');
								delay(10);
								writeln('    `. `-.           /    /                    `-..^._             |            ');
								delay(10);
								writeln('      |._|    _.    /    /                            `._           .           ');
								delay(10);
								writeln('      `...:-- --+..    ,                               /            |           ');
								delay(10);
								writeln('           ._  `|   ,-        _..._                   j     \       |           ');
								delay(10);
								writeln('            |` |   /       ,-      `-.__              |      L      |           ');
								delay(10);
								writeln('            |  |  /      ,                            |      |      |           ');
								delay(10);
								writeln('            |_,         /         _,-                  .     |      |           ');
								delay(10);
								writeln('           ,   ,   |  ,         ,|            ,..._     \    |      |           ');
								delay(10);
								writeln('          ,     \ j          _." |           /     `-.__          ,             ');
								delay(10);
								writeln('           +._    |       , |    |          /        ,     .     /              ');
								delay(10);
								writeln('           |  `._  `-  .:|  |     .       -                     j               ');
								delay(10);
								writeln('                |`      |   |     |                             |               ');
								delay(10);
								writeln('            `.  |       |--      _|        .                    |               ');
								delay(10);
								writeln('              \ |        ---- """           \      __,....-+----                ');
								delay(10);
								writeln('              |                              `---""      .                      ');
								delay(10);
								writeln('              `. `.                                     ,                       ');
								delay(10);
								writeln('                `" \_...-""" --..         _+          ,                         ');
								delay(10);
								writeln('                                  -.   `-   `.  ."-..                           ');
								delay(10);
								writeln('                      `-..._            _____,.                                 ');
								delay(10);
								writeln('                            `--.....,-"                                         ');
							end;

			'Magicarpe':
							begin
								delay(10);
								writeln('                                    __.--.._,- ""-.                             ');
								delay(10);
								writeln('                                 ,-  .  ,   .-"  -.`.       .--.                ');
								delay(10);
								writeln('                               ,     |  |   `-.    \ \       `-.|               ');
								delay(10);
								writeln('                              /       .   /    `.   \ \        ||               ');
								delay(10);
								writeln('                             /         `..`.    `.   \ .       ||               ');
								delay(10);
								writeln('                            /        . .    `.    \   . .       .               ');
								delay(10);
								writeln('                   ."-.    .  ,"" -. | |      \    \   `.`.__, .                ');
								delay(10);
								writeln('                    `. `. .   |     `. |       \    .    `-..-                  ');
								delay(10);
								writeln('          _______     .  `|   |       .         .   |...--._                    ');
								delay(10);
								writeln('          `.     `"--.         .      | .        .  |""  "-._"-._               ');
								delay(10);
								writeln('            `.             \    `-._.. . .       |  |---.._  `-.__"-..          ');
								delay(10);
								writeln('       -.     `.           |\           `.`      |  | `-.  `-._   +"-           ');
								delay(10);
								writeln('       `.`.     `-.        | `            .`.       | `. `.    `,"              ');
								delay(10);
								writeln('         `.`.      `.      |   .           ` `      `.  \  `   /                ');
								delay(10);
								writeln('         | `.`.    __`.    |`/  `.     ...  `.`.     |   `.   .                 ');
								delay(10);
								writeln('         |   \ .  `._      | `. / `. . .  |   \ \    |     \  |                 ');
								delay(10);
								writeln('         |.   ` \    `-.   |   \   . . /  |    \ \   |      ._                  ');
								delay(10);
								writeln('         | `.  `.\      `. |    \ / ,  .  |_    . \   -.                        ');
								delay(10);
								writeln('        ,     .  .\       `|     .   / |  | `-...\ \    `._                     ');
								delay(10);
								writeln('        `.     `.  \       |.     / .  |  |         .      `-.                  ');
								delay(10);
								writeln('         .`._    \` \      | `. /      |  |       | |       ,.                  ');
								delay(10);
								writeln('          .  `-.  \`.\    ,|   //      |  |__  .  | |      |                    ');
								delay(10);
								writeln('          |     `._`| `--  `  //  .    |     `"  /| |   . -                     ');
								delay(10);
								writeln('                   `|       `//        |   .    / | |   |                       ');
								delay(10);
								writeln('         /....._____|       //   .  ___|   |   /  | |  ,|                       ');
								delay(10);
								writeln('        .         _.       /, _.--" -._ `".| ,    | |.                          ');
								delay(10);
								writeln('        |      _,  / ___   `- .        `. _|      |,                            ');
								delay(10);
								writeln('        |  _,-"  , .    `-.._  `.      _,          `                            ');
								delay(10);
								writeln('         -"   _, ,           "- ....--                                          ');
								delay(10);
								writeln('       /  _.-"_.                                                                ');
								delay(10);
								writeln('      /_, _,-                                                                   ');
								delay(10);
								writeln('    . _.-                                                                       ');
								delay(10);
								writeln('     "                                                                          ');
							end;

			'Pascal'	:
							begin
								delay(10);
								writeln('               ________________________________________________                 ');
								delay(10);
								writeln('              /                                                \                ');
								delay(10);
								writeln('             |    _________________________________________     |               ');
								delay(10);
								writeln('             |   |                                         |    |               ');
								delay(10);
								writeln('             |   |  C:\> _                                 |    |               ');
								delay(10);
								writeln('             |   |                                         |    |               ');
								delay(10);
								writeln('             |   |                                         |    |               ');
								delay(10);
								writeln('             |   |                                         |    |               ');
								delay(10);
								writeln('             |   |                                         |    |               ');
								delay(10);
								writeln('             |   |                                         |    |               ');
								delay(10);
								writeln('             |   |                                         |    |               ');
								delay(10);
								writeln('             |   |                                         |    |               ');
								delay(10);
								writeln('             |   |                                         |    |               ');
								delay(10);
								writeln('             |   |                                         |    |               ');
								delay(10);
								writeln('             |   |                                         |    |               ');
								delay(10);
								writeln('             |   |                                         |    |               ');
								delay(10);
								writeln('             |   |_________________________________________|    |               ');
								delay(10);
								writeln('             |                                                  |               ');
								delay(10);
								writeln('              \_________________________________________________/               ');
								delay(10);
								writeln('                     \___________________________________/                      ');
								delay(10);
								writeln('                  ___________________________________________                   ');
								delay(10);
								writeln('               _-     .-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.  --- `-_                ');
								delay(10);
								writeln('            _- .-.-. .---.-.-.-.-.-.-.-.-.-.-.-.-.-.-.--.  .-.-.`-_             ');
								delay(10);
								writeln('         _- .-.-.-. .---.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-`__`. .-.-.-.`-_          ');
								delay(10);
								writeln('      _- .-.-.-.-. .-----.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-----. .-.-.-.-.`-_       ');
								delay(10);
								writeln('   _- .-.-.-.-.-. .---.-. .-------------------------. .-.---. .---.-.-.-.`-_    ');
								delay(10);
								writeln('  :-------------------------------------------------------------------------:   ');
								delay(10);
								writeln('  `---._.-------------------------------------------------------------._.---    ');
							end;
		end;

        ////gotoxy(30,20);write('PV-20');
END;


end.

